### PR TITLE
Add share() method to share instance

### PR DESCRIPTION
**Pull request by kenjis**

### CODE REVIEW

**Comment by kenjis** [comment]
I know some DiC have method to a share an already existing instance, but I don't need it now.

If it is needed, how about add inject() method?

``` php

$obj = new ArrayObject;
$container = new League\Di\Container;
$container->bind('ArrayObject')->inject($obj);
```

**Comment by kenjis** [comment]
Pimple 2.0 changed the default to share instance.

> The reasoning is quite simple: services are 99.9% shared (I don't even have an example for a prototype service).
> https://github.com/fabpot/Pimple/pull/83

How do you think?

**Comment by philsturgeon** [comment]
This has been deprecated in favor of [Orno\Di](https://github.com/orno/di), which this was very closely modeled on. They've since has a 2.0 so you might as well head over there and see if they take care of this functionality. If not, make an issue I guess. :)

**Comment by kenjis** [comment]
@philsturgeon I'm sorry, I can't get what you exactly say.

Orino\Di has singleton() method.
https://github.com/orno/di/blob/master/src/Orno/Di/Container.php#L98
and has functionality to add already instantiated object.
https://github.com/orno/di/blob/master/src/Orno/Di/Container.php#L78

Do you say we should implement the functionality like Orino\Di?

**Comment by philsturgeon** [comment]
I'm saying this repo is deprecated (closing) so you should use their package instead. :)—

**Comment by kenjis** [comment]
Oh, I see. Thank you.

**Pull request closed without merging**
